version: 2
jobs:
  build:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: |
          TAG=1.$CIRCLE_BUILD_NUM
          docker build -t romanisko/heroku-cli-deploy:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push romanisko/heroku-cli-deploy:$TAG
          docker tag romanisko/heroku-cli-deploy:$TAG romanisko/heroku-cli-deploy:latest
          docker push romanisko/heroku-cli-deploy:latest
